#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
import sys, select, termios, tty

msg = """
AUTO-STOP MODE
---------------------------
w/s : Forward/Backward
a/d : Rotate Left/Right
Release Keys : STOP INSTANTLY

CTRL-C to quit
"""

class WASDTeleop(Node):
    def __init__(self):
        super().__init__('wasd_teleop')
        self.publisher_ = self.create_publisher(Twist, 'cmd_vel', 10)
        self.speed = 0.5
        self.turn = 2.0
        self.settings = termios.tcgetattr(sys.stdin)

    def getKey(self):
        # Timeout is 0.1 seconds. If no key is pressed, it returns ''
        tty.setraw(sys.stdin.fileno())
        rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
        if rlist:
            key = sys.stdin.read(1)
        else:
            key = ''
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.settings)
        return key

    def run(self):
        print(msg)
        try:
            while True:
                key = self.getKey()
                
                # 1. ALWAYS Default to ZERO (Stop)
                target_linear_vel = 0.0
                target_angular_vel = 0.0

                # 2. Only change speed if a specific key is pressed
                if key == 'w' or key == 'W':
                    target_linear_vel = self.speed
                elif key == 's' or key == 'S':
                    target_linear_vel = -self.speed
                elif key == 'a' or key == 'A':
                    target_angular_vel = self.turn
                elif key == 'd' or key == 'D':
                    target_angular_vel = -self.turn
                elif key == '\x03':  # CTRL-C
                    break

                # 3. Publish EVERY time
                # If you let go of keys, 'key' is empty, so we publish 0.0 here.
                twist = Twist()
                twist.linear.x = float(target_linear_vel)
                twist.angular.z = float(target_angular_vel)
                self.publisher_.publish(twist)

        except Exception as e:
            print(e)

        finally:
            # Final safety stop
            twist = Twist()
            twist.linear.x = 0.0
            twist.angular.z = 0.0
            self.publisher_.publish(twist)
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, self.settings)

def main(args=None):
    rclpy.init(args=args)
    node = WASDTeleop()
    node.run()
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
